import pkg from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pkg;
const b = await chromium.launch();
const p = await b.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
const reqs=[];
p.on('request',r=>{ const u=r.url(); if(/styles\.css|api\.js|app\.js/.test(u)) reqs.push(u.split('/').pop()); });
await p.setViewportSize({width:1280,height:900});
await p.goto('http://127.0.0.1:8111/index.html',{waitUntil:'networkidle'});
await p.waitForSelector('#email',{timeout:15000});
await p.fill('#email','john@church.org'); await p.fill('#pw','demo1234');
await p.click('button:has-text("Sign in")');
await p.waitForSelector('.stat-grid-dash',{timeout:15000});
await p.waitForTimeout(700);
const tops = await p.$$eval('.stat-grid-dash .stat', els=>els.map(e=>Math.round(e.getBoundingClientRect().top)));
console.log('cache-busted requests:', JSON.stringify(reqs));
console.log('dashboard cards:', tops.length, '| one row:', new Set(tops).size===1);
console.log(errs.length?'ERRORS:'+errs.join(';'):'no page errors — app boots fine with cache-busting');
await b.close();
